language: node_js
node_js:
  - lts/*
install:
  - cd docs
  - npm install
script:
  - npm run build
  - ls -l src/.vuepress/dist
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./src/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: github-pages
  fqdn: docs.mercurywallet.com
  on:
    branch: main

